"""empty message

Revision ID: 3095912c8289
Revises: b1d07920bdb1
Create Date: 2020-05-30 13:56:07.243718

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3095912c8289'
down_revision = 'b1d07920bdb1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todos', 'completed',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###

    op.execute('UPDATE todolists SET completed = False WHERE completed IS NULL;')

    op.alter_column('todolists', 'completed', nullable=False)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todos', 'completed',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
